### ISSUE TITLE
Feature request/Capture TAB inside editor

### ISSUE THREAD

**Issue by pjamar** [rchrd2/TextEditor#4]
I would like to be able to use the TAB key inside the editor. Right now it will cycle through the elements on the web page and the browser address text box.

Maybe this can help you http://stackoverflow.com/questions/3362/capturing-tab-key-in-text-box

Thanks!

**Comment by rchrd2** [comment]
Hi @pjamar that seems like a good idea. I'll try this out when I have some time. Thanks for the suggestion.

**Comment by pjamar** [comment]
My pleasure. Thanks for your work, the Text Editor look fantastic :)

**Comment by rchrd2** [comment]
Hi @pjamar. I just published a new release that supports the TAB key. Pressing the TAB key inserts a real tab (eg "\t"). If you wouldn't mind, could you please "star" this repo? Thanks!

**Comment by pjamar** [comment]
Starred the repo!
I've tested it and works perfectly, thank a lot!! :)

**Comment by rchrd2** [comment]
No problem! Let me know if you have any more ideas.
